name: Deploy on Google Cloud Platform

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          registry: us-central1-docker.pkg.dev

      - name: Build and Push Container
        run: |-
          docker build -t us-central1-docker.pkg.dev/bots-for-telegram/cloud-run-source-deploy/delduca:latest .
          docker push us-central1-docker.pkg.dev/bots-for-telegram/cloud-run-source-deploy/delduca:latest"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: delduca
          image: us-central1-docker.pkg.dev/bots-for-telegram/cloud-run-source-deploy/delduca:latest
